<br />
<ul>
<li>Version 0.0.1 - 14 June 2010
 <ul>
 <li>Initial Release</li>
 </ul>
</li>
<li>Version 0.0.2 - 7 September 2010
 <ul>
 <li></li>
 </ul>
</li>
<li>Version 0.0.4 - 4 June 2012
 <ul>
 <li></li>
 </ul>
</li>
<li>Version 0.0.8 - 1 October 2013
 <ul>
 <li></li>
 </ul>
</li>
<li>Version 0.1 - April 2015
 <ul>
 <li>Support CMSMS up to 1.11.x</li>
 <li>UI tweaks</li>
 <li>Bugfixes</li>
 <li></li>
 </ul>
</li>
</ul>
