<br />
<ul>
<li>Version 0.0.1 - 14 June 2010
 <ul>
 <li>Initial Release</li>
 </ul>
</li>
<li>Version 0.0.2 - 7 September 2010
 <ul>
 <li></li>
 </ul>
</li>
<li>Version 0.0.4 - 4 June 2012
 <ul>
 <li></li>
 </ul>
</li>
<li>Version 0.0.8 - 1 October 2013
 <ul>
 <li></li>
 </ul>
</li>
<li>Version 0.2 - 31 January 2016
 <ul>
 <li>UI tweaks</li>
 <li>Support CMSMS 1.11.x,1.12.x,2+</li>
 <li>Deprecate support for triggering via pretty-url</li>
 <li>Bugfixes</li>
 </ul>
</li>
</ul>
